### PR TITLE
Add all professional videos and those for mod 1 and 2

### PR DESCRIPTION
**Pull request by joelostblom**
This is easier to keep track of than referencing a list, especially since we now have so many separate videos

### CODE REVIEW

**Comment by joelostblom** [comment]
This is ready for review @armanawn @flor14 . It is enough if one of you do it, so whoever has time, go ahead and add yourself as a reviewer when you can work on it. When you review, double check that the right video is in the right place and that the start and end times make sense so that nothing is cut off.

When you add your own videos, I have set it up so that you only need to do two things:

1. Edit `locale.json` to add the suffix/ID of the YouTube link instead of the placeholder text `"moduleN-link"`.
2. Insert the appropriate timestamps inside `chapters/en/moduleN.md`.

You can [view this commit to see what it looked like when I did the two steps above for module 1](https://github.com/UBC-MDS/ds-toolbox/pull/90/commits/db7f581e1e3f59f3f3c7944d4c5a39d1bfaea66d).

We're almost there!

**Comment by armanawn** [comment]
Everything looks good to me.

**Comment by armanawn** [comment]
@joelostblom I've re-ordered the video links inside `locale.json` so that everything is in sequential order and more readable (and I've changed the `shot` tag in your module 1 and 2 accordingly). If you don't like this version, please let me know and I'll revert to the original version.

**Comment by joelostblom** [comment]
Thanks for adding your videos @armanawn ! I looked through all your and my slides and it looks like the correct video is always in the correct place. My idea with the numbering was that we would have `shot = module number` to make it easy to keep track of but I like your sequential order too, so I'm good either way. Could you just update the shot numbers for module 3, 4, and 5? I had these setup previously, but now they are out of sync with the new order.

**Comment by armanawn** [comment]
Awesome! For sure, I'll update the shot numbers for module 3, 4, and 5 as well.

@flor14 Do you also use one single video for all of your slide decks in each of your modules? I'm asking because if that's the case, I can adjust the shot numbers in the way I've done it for modules 1, 2, 6, 7, and 8.

**Comment by flor14** [comment]
@armanawn yes, I am doing the same

**Comment by joelostblom** [comment]
Looks good! I am merging this and @flor14 you can open a new PR with your video links and timestamps.

**Pull request merged**
